
[entryPoints]
  [entryPoints.app]
    address = ":80"
  [entryPoints.app.http]
    [entryPoints.app.http.redirections]
      [entryPoints.app.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[accessLog]

[api]
dashboard = true

[providers]
  [providers.docker]
    exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
  email = "rahmatovolim3@gmail.com"
  storage = "/certificates/acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "app"