"""add posts in user table

Revision ID: 415653ec266b
Revises: 16499f054678
Create Date: 2023-09-06 18:53:39.787727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415653ec266b'
down_revision = '16499f054678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
