"""fix relation name

Revision ID: 43203e572676
Revises: 415653ec266b
Create Date: 2023-09-06 18:55:06.293992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43203e572676'
down_revision = '415653ec266b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
